### ISSUE TITLE
Aptitude of current API for common scenarios

### ISSUE THREAD

**Issue by sarumjanuch** [rolftimmermans/zeromq-ng#32]
Hi there! I came from https://github.com/zeromq/zeromq.js, where i started reading the code and my WTF per second was over 9000.  I was shocked that for so many years, this is the best what node community did in zmq field. But then I traped on https://github.com/zeromq/zeromq.js/issues/189, which is absolutely reasonable, and this is how i get here. Now reading your documentation i found:
> Only one call to send() may be executed simultaneously. Do not call send() again on the same socket until the returned promise resolves. Make sure to use await or similar.

Maybe I don't understand that correctly, but this makes absolutely no sense from library user perspective. This means that if I will need to implement somehow useable broker based on zm.ROUTER, I will need to implement my own queue/buffer which will only be existing because of the logic mentioned above?

**Comment by rolftimmermans** [comment]
Whether or not `send()` blocks depends on the socket type and options. This is completely analogous to libzmq itself. The only difference is that `send()` (without `await`) does not block in Node.js; so that other code can be scheduled at the same time.

So to be clear: libzmq does the queueing for you. The reason that `await send()` is necessary is that it depends on the socket type, socket options and high watermark whether or not send should block until a message could be queued. If it does not block and just queues the message the promise will resolve very very quickly.

Does that answer your question?

**Comment by sarumjanuch** [comment]
I believe yes. In the code, i see that in send, you always set ZMQ_DONTWAIT flag https://github.com/rolftimmermans/zeromq-ng/blob/master/src/socket.cc#L210,  which means that, zmq_msg_send, should immediately return an error in case of zmq_socket is non-writable, whether the HWM reached, or any other conditions, and following forward thru the code, the promise will be rejected in case of error, and resolved in case of success, I don't see any async stuff there. So based on all of the above, send will always (or not?) resolve or reject immediately. This raises a new question: why send is using promises if, in case of ZMQ_DONTWAIT, it can simply return (or not)?

**Comment by rolftimmermans** [comment]
That code is only for the synchronous implementation. Take a look at https://github.com/rolftimmermans/zeromq-ng/blob/master/src/socket.cc#L385 and beyond to see all scenarios for sending. This is all to make sure behaviour matches libzmq while avoiding blocking other Node.js operations.

**Comment by sarumjanuch** [comment]
Ok, now I see. Well, let me share my thoughts, maybe they will make some sense to you. Again this is just my opinion. You have made implementation something between low level and high level.  Based on what I see and understand, you have made poller based on UV loop, which absolutely makes sense.  It allows Node to poll for FD events without blocking. Now  in case of low-level implementation, I would expect to use such poller in node land to explicitly ask it for events with control on which events i want, and using timeouts i need, and with ability to ask poller only when i need, this would be as musch as close and fair to libzmq behaviour, except it will allow async poll via uv loop.  Now, due to edge-triggered nature and zmq fd's are not true POSIX fd's, i would expect library to expose has_event functionality, to check wether triggered events by poller are "true", or even to check wether i sould send immediatly, or ask poller to monitor write event. Also there should be something like SendSync, RecvSync which will sync call zmq_send/recv, with DONTWAIT option and return result, i belive poller.trigger should stay in NAPI land at every send/receive.  Having all of the mentioned above, will allow user to have control and more explicit behaviour in Node land, and will be much closer to libzmq semantic then it is now, as now i came here and was confused: "are this low level bindings or high lvl bindings?". And it appears that it is neither, it is something in between, and restrictions that mentioned in documentation, has very unclear motivation, until you actually open the code, and ask author... What do you think?

**Comment by rolftimmermans** [comment]
Thanks for sharing your thoughts, I will give it some more thought.  In the mean time, would you mind giving some straw-man examples of what you describe:

>>> Now in case of low-level implementation, I would expect to use such poller in node land to explicitly ask it for events with control on which events i want, and using timeouts i need, and with ability to ask poller only when i need

Maybe there are use cases I haven't been able to consider. I believe the implementation as it is should be low level enough to make everything possible, while sticking as close as possible to libzmq semantics. `send()` really does (or should) behave identically to how it would work in C.

But I like to be proven wrong here, this is (still) an experiment and a complete overhaul of the API is not out of the question if it makes the end result better!

**Comment by rolftimmermans** [comment]
Thanks for sharing! Just to make sure I understand you completely – which use case does this allow you to solve that the current API does not address in your opinion?

**Comment by sarumjanuch** [comment]
Lower level, controlled, explicit implementation, with as less as possible unique magic behind the curtains. Especially in case of Send. From high-level API I would expect, my messages to be queued inside of the library, and from low-level, I would expect pass-thru to zmq_send_msg. You have "send", that is half pass-thru, half something that is not low and not high enough, which force me to implement queueing in Node userland, and library don't provide me the ability to have explicit control in Node land.

**Comment by sarumjanuch** [comment]
I have no ability right now,  to know, can I send msg or not, without actually trying to send one, or reference to some state, which will hold previous send attempts and outcomes.

**Comment by rolftimmermans** [comment]
Right, but what is a concrete use case that you want to implement where you run into this? What use case forces you to implement queueing in Node? That certainly is undesirable, but I do not grasp your use case to be able to look at it from different angles...

**Comment by rolftimmermans** [comment]
Let me provide an example. You mention wanting to write a broker. Say that you want to implement a broker like in this image from the ZMQ guide: https://raw.githubusercontent.com/booksbyus/zguide/master/images/fig17.png

It would something like this with the Next Gen API:

```js
async function loop() {
  const in = new zmq.Router()
  const out = new zmq.Dealer()
  await in.bind("tcp://*:5559")
  await out.bind("tcp://*:5560")
  for await (const [msg] of in) {
    await out.send(msg)
  } 
}

loop()
```

This code should be an equivalent implementation of http://zguide.zeromq.org/c:rrbroker

Since you mention a few issues you run into – I wonder what kind of a broker are you writing that causes these issues to come up? I would like to make sure I really thoroughly understand the situation before I comment more on possible solutions... I might be looking in entirely the wrong direction otherwise.

**Comment by sarumjanuch** [comment]
I believe you will run into this in any situation when the socket will be blocked? In more real-life example, you may have a ROUTER, which routes some msgs between many DEALERS,  and one of the dealer's socket may become blocked, but others dealers keep sending messages to it via ROUTER, now ROUTER should buffer some certain amount of messages before socket will become writable again, and still should not block the main loop. And of course error handling. Does this make sense?

**Comment by sarumjanuch** [comment]
In the example that you have provided, you are sequentially reading from the router and sequentially writing to one dealer, you don't read next until original msg is written, and promise resolved, but you can't afford this in more complex scenarios, you have to read whenever there is an event that socket is readable.  
Imagine something like [this ](https://www.safaribooksonline.com/library/view/zeromq/9781449334437/ch04s08.html), where Workers and Clients are DEALER's and a broker is ROUTER, which using "well knwon" identities, to do routing.

**Comment by rolftimmermans** [comment]
> In the example that you have provided, you are sequentially reading from the router and sequentially writing to one dealer, you don't read next until original msg is written, and promise resolved.

Yes, that's the goal too – the Router will not be read from if messages cannot be delivered.

But I see your point; when implementing the Majordomo pattern you wish to keep reading and delivering incoming messages even when one type of message cannot be delivered immediately because of a Dealer socket that blocks.

I will give this some more thought. Ideally we find an API surface that:
1) works for all reasonable scenarios
2) is easy to use correctly and difficult to use incorrectly, gently guiding users to best practices
3) does not swallow errors but exposes by default
4) is as close as possible to libzmq

Priority is roughly in that order as far as I'm concerned: these were also the guiding principles when designing the API that is currently there – although of course I was bound to overlook scenarios addressed by point 1.

If you have any additional ideas feel free to pitch in!

**Comment by sarumjanuch** [comment]
One more observation. I have just done very stupid benchmark, where I spawn two processes (DEALER and ROUTER) and send 5M messages between them, so on my machine zeromq-nq almost twice slower then original, and I hope that it is because of async stuff here and there, and not because of the price node <-> cpp transitions, have you tested this? Current API is fine, it just lacks something like sendSync/recvSync, and some way to catch poller readable/writable states, as I mentioned previously.

**Comment by rolftimmermans** [comment]
Care to share the benchmark? I did do a few benchmarks of the new code vs the existing lib; they were not all conclusive one way or the other, I'd like to avoid performance being significantly worse.

**Comment by sarumjanuch** [comment]
Simplest possible benchmark: https://pastebin.com/GrZdTP3Q. run router then dealer and wait.

**Comment by rolftimmermans** [comment]
@sarumjanuch I have given much thought to this issue.

As it seems right now all scenarios are possible with the current API. I will explain my reasoning below and also add some of this text to the README for clarification. To validate this I have also partially implemented a broker based on the MDP protocol. It is available in the examples directory.

First of all, the reason for disallowing multiple `send()` calls simultaneously is that it could create an implicit queue of unsendable outgoing messages (wrapped in Promise objects). This would circumvent any high water mark or related settings. Such an implementation could even exhaust all system memory and cause the Node.js process to abort. This is not entirely hypothetic, it is a real problem with the current version of zeromq.js which does queue in JavaScript automatically – in fact, I ran into this in the benchmark program you linked.

Only in rare occasions will a call to `send()` that does not resolve immediately be undesired. The following are some scenarios that I have considered, and how to approach them with this API:

* If you wish to send a message, you can use `await send(...)`. ZeroMQ socket types have been designed to give the correct blocking behaviour on the chosen socket type in almost all cases:

  * If sending is not possible, it may just be better to wait than to continue as if nothing happened. For example, on a `Request` socket, you can only receive a reply once a message has been sent; so waiting until a message could be queued before continuing with the rest of the program (likely to read from the socket) is required.

  * Certain socket types (such as `Router`) will always allow queueing messages and `await send(...)` won't delay any code that comes after. This makes sense for routers, since typically you don't want a single send operation to stop the handling of other incoming or outgoing messages.

* If you wish to send on an occasionally **blocking** socket (for example on a `Router` with the `mandatory` option set, or on a `Dealer`) and dropping a message is better than blocking, then you can set the `sendTimeout` option to `0` to effectively force `send()` to always resolve immediately. Of course any exceptions when sending is not possible should be dealt with appropriately.

* If you wish to send on a socket and **messages should be queued before they are dropped**, you can implement a simple queue in JavaScript. Such a queue is not provided by this library right now. I'm hesitant to add it since I think most real applications deal with it in more complex, domain-specific ways. They might retry the message, return a status message to the client, etc. I have added an example implementation to the examples directory, though.

Thanks a lot for your feedback so far. I'll continue working on the NG bindings and hope to merge them back to the zeromq.js project soon. 

Please, if you have any issues using the NG API feel free to open a new issue and I'll do my best to help.

**Comment by rolftimmermans** [comment]
Closing this issue, as it has been included in documentation.
