### ISSUE TITLE
seems there is memory leak

### ISSUE THREAD

**Issue by crazybits** [rolftimmermans/zeromq-ng#50]
seems there is memory leak, sample code below, the heap usage keep increasing and OOM  at last, any idea?
```
async function run() {

	let sock = new zmq.Pull
	sock.connect("tcp://127.0.0.1:5556")
	logger.info('start zmq comsumer on port 5556')

	while (!sock.closed) {
		const [rawMsg] = await sock.receive()
		let msgType = rawMsg.readUIntLE(0, 4)
		let msgString = rawMsg.toString('utf8', 8, rawMsg.length)
         }
}
run()
```

**Comment by rolftimmermans** [comment]
I know it's been a while since you posted this, but is there some code missing? This example seems to stop at `await sock.receive()` without any further memory usage or activity.

**Comment by sarumjanuch** [comment]
I actually also experience the same thing, and can't understand is it v8 stuff, or this lib, or both. Try run this:
worker.js:
```

const zmq = require('zeromq-ng');
const socket = new zmq.Router;
let counter = 0;

async function run() {
    try {
        await socket.bind("tcp://127.0.0.1:3000");
    } catch (e) {
        console.log(e);
    }
    while (!socket.closed) {
        const [identity, msg] = await socket.receive();
        if (!counter) {
            console.time("message");
        }

        counter++;

        if (counter >= 100000) {
            console.log("received 100000 msgs in ");
            console.timeEnd("message");
            counter = 0;
        }
    }
}

run();

```


dealer.js:

```

const zmq = require('zeromq-ng');
const socket = new zmq.Dealer;

async function run() {

    try {
        await socket.connect("tcp://127.0.0.1:3000");
    } catch (e) {
        console.log(e);
    }

    while (!socket.closed) {
        try {
            await socket.send('Hello World!');
        } catch (e) {
            console.log(e);
        }
    }
}

run();

```

The router process will eat all your server memory, but will not crush. When you stop the dealer, the router will never GC and give back eaten memory. This is tied to socket.receive, as the dealer process will not touch more memory after the start.

**Comment by sarumjanuch** [comment]
setting receiveHighWaterMark fixes situation.

**Comment by rolftimmermans** [comment]
Hm, interesting. It seems this is a side effect of a performance optimisation I made where `receive()` will immediately return a resolved promise if the socket has any messages queued.

My expectation is that this will only occur in synthetic programs. For example, adding the following line in `worker.js` will limit memory usage to about 100MB:

```js
if (counter >= 100000) {            
    // add this line:
    await new Promise(resolve => setTimeout(resolve, 0))
    // ...
```

The program in `worker.js` will never pause until the socket has no messages. Since ZMQ uses background I/O threads that will not happen in this example.

So what it means is that either the async message cleanup or the GC itself will not run. The line with `setTimeout` simulates a scenario where the Node event queue becomes empty, which will free up memory from unused messages.

I would be surprised if this were in issue in actual deployments. I will nevertheless have a look to see if there is an easy fix for this behaviour.

**Comment by rolftimmermans** [comment]
I think this is a bug in Node.js. GC runs fine, but the finalizers are never called if the event loop is not allowed to continue. It seems similar to https://github.com/nodejs/node/issues/26667, for which investigation is still pending.

**Comment by rolftimmermans** [comment]
For small messages this is no longer an issue since 01773f2d97f65badaa9e85be55e7d152d6b42df6. However, larger buffers will still remain in memory until the next event loop tick. This won't happen until there are no messages on the socket.

While this may seem scary behaviour, I'm not sure there is a practical situation where this would actually happen.

I'm closing this for now, but feel free to continue the discussion.
